# Generated by Django 5.2.7 on 2025-11-11 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_servicetype_alter_barber_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], help_text='Day of the week (0=Monday, 6=Sunday)')),
                ('start_time', models.TimeField(blank=True, help_text='Default start time for this day', null=True)),
                ('end_time', models.TimeField(blank=True, help_text='Default end time for this day', null=True)),
                ('is_available', models.BooleanField(default=True, help_text='Toggle for a default day off')),
                ('barber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_availability', to='main.barber')),
            ],
            options={
                'verbose_name': 'Weekly Availability',
                'verbose_name_plural': 'Weekly Availabilities',
                'ordering': ['barber', 'day_of_week'],
                'unique_together': {('barber', 'day_of_week')},
            },
        ),
    ]
