# Generated by Django 5.2.7 on 2025-11-18 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_weeklyavailability'),
    ]

    operations = [
        migrations.AddField(
            model_name='barber',
            name='is_approved',
            field=models.BooleanField(default=False, help_text='Indicates if the barber has been approved by an admin'),
        ),
    ]
