# Generated by Django 5.2.7 on 2025-12-02 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_reservation_status'),
        ('main', '0005_barber_is_approved'),
    ]

    operations = [
    ]
