# Generated by Django 5.2.7 on 2025-12-02 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_merge_20251202_0217'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='booking_source',
            field=models.CharField(choices=[('online', 'Online'), ('walk_in', 'Walk-in')], default='online', help_text='Source of the booking: Online (customer-created) or Walk-in (admin-created)', max_length=20),
        ),
    ]
